### ISSUE TITLE
Fatal error: Class 'extResourceUpdateManagerController'

### ISSUE THREAD

**Issue by elebediev** [BobRay/ClassExtender#2]
Please, help! When we create resource and save, we have got this error:
Fatal error: Class 'extResourceUpdateManagerController' not found in ..../manager/controllers/default/resource/resource.class.php on line 80

Version Modx Revolution 2.2.15-pl (traditional)

**Comment by BobRay** [comment]
Does it happen when you edit and save existing resources?
Does it always happen when you create a new resource?
Is the error in the Error log or on the screen?
Is the resource saved?

Check the path in the extresource namespace.

Try deleting all files in the core/cache directory.

**Comment by elebediev** [comment]
The error occurs when I save the resource. The error is displayed on the screen.The log is overwritten. Check please. That access to the site:

**Comment by BobRay** [comment]
I deleted your credentials from the previous message. You probably don't want them to be public. ;)

I didn't find anything obvious on your site. I'll see if I can duplicate the problem here.

It might help if I could look at your database in PhpMyAdmin, but don't put the credentials here! If you want to send them, you can PM me on the MODX forums or use the contact page at http://bobsguides.com

**Comment by BobRay** [comment]
I think I may see the problem. Your site domain seems to be http://423339.retmodx.web.hosting-test.net/ but [[++core_path]] resolves to /home/retmodx/testmodx.com.ua/www/core/, which seems unlikely. 

Carefully replacing [[++core_path]] with the actual path (note _not_ the URL) to your modx core in the extension_packages System Setting might fix things. Be sure it ends with a slash.
